"""Registro de fuentes: id → (función, etiqueta, institución, acceso, nivel geográfico, qué había en la hoja)."""
from . import gobpe, others, senamhi

SOURCES = {
    "senamhi_avisos": dict(fn=senamhi.avisos, org="SENAMHI", name="Avisos meteorológicos", via="HTML + WFS GeoServer",
                           geo="Polígono → provincia", sheet="Muerto desde 07-07-2026 (#269), sin nivel"),
    "senamhi_uv": dict(fn=senamhi.uv, org="SENAMHI", name="Índice UV", via="JSON", geo="Provincia (ubigeo)",
                       sheet="Muerto desde 07-07-2026, solo capitales"),
    "senamhi_pronostico": dict(fn=senamhi.pronostico, org="SENAMHI", name="Pronóstico por ciudad", via="HTML", geo="Ciudad",
                               sheet="Muerto desde 07-07-2026, solo capitales"),
    "senamhi_hidro": dict(fn=senamhi.hidro, org="SENAMHI", name="Avisos hidrológicos", via="GeoJSON", geo="Estación → distrito",
                          sheet="No existía"),
    "indeci": dict(fn=others.indeci, org="INDECI · COEN", name="Reportes de emergencia", via="RSS", geo="Distrito (texto)",
                   sheet="No existía"),
    "igp": dict(fn=others.igp, org="IGP", name="Sismos", via="JSON", geo="Coordenadas", sheet="Vivo, en texto libre"),
    "serfor": dict(fn=others.serfor, org="SERFOR", name="Focos de calor e incendios", via="ArcGIS REST",
                   geo="Coordenadas + ubigeo", sheet="Vivo, agregado en texto"),
    "ingemmet": dict(fn=others.ingemmet, org="INGEMMET", name="Zonas críticas en alerta", via="ArcGIS REST",
                     geo="Coordenadas + distrito", sheet="Muerto desde 27-04-2026"),
    "enfen": dict(fn=others.enfen, org="ENFEN", name="Estado del sistema de alerta", via="WordPress + PDF", geo="Nacional",
                  sheet="No existía"),
    "firms": dict(fn=others.firms, org="NASA FIRMS", name="Focos de calor (respaldo)", via="CSV abierto", geo="Coordenadas",
                  sheet="—"),
    "indeci_fotos": dict(fn=lambda: __import__("mesa.indeci_pdf", fromlist=["run_pending"]).run_pending(15),
                         org="INDECI · COEN", name="Fotos y datos de los PDF", via="PDF (anexo fotográfico)",
                         geo="Distrito (del reporte)", sheet="No existía"),
    "com_pnp": dict(fn=gobpe.noticias("pnp"), org="PNP", name="Comunicados PNP", via="gob.pe JSON", geo="Sin ubicación (texto)",
                    sheet="No existía"),
    "com_provias": dict(fn=gobpe.noticias("pvn"), org="PROVIAS Nacional", name="Notas de prensa PROVIAS", via="gob.pe JSON",
                        geo="Sin ubicación (texto)", sheet="No existía (única vía a sus emergencias viales)"),
    "com_mtc": dict(fn=gobpe.noticias("mtc"), org="MTC", name="Notas de prensa MTC", via="gob.pe JSON", geo="Sin ubicación (texto)",
                    sheet="No existía"),
    "com_mininter": dict(fn=gobpe.noticias("mininter"), org="MININTER", name="Notas de prensa MININTER", via="gob.pe JSON",
                         geo="Sin ubicación (texto)", sheet="No existía"),
    "sidpol": dict(fn=gobpe.sidpol, org="PNP · MININTER", name="Denuncias policiales (SIDPOL)", via="CSV datos abiertos",
                   geo="Distrito → provincia", sheet="No existía"),
    "respaldo": dict(fn=lambda: __import__("mesa.backup", fromlist=["run"]).run(), org="Colector", name="Respaldo de datos",
                     via="Carpeta de MESA_BACKUP", geo="—", sheet="—", internal=True),
    "provias": dict(fn=others.provias, org="PROVIAS Nacional", name="Servidor de emergencias viales", via="—", geo="Provincia/distrito (hoja)",
                    sheet="MTC vivo; PROVIAS muerto desde 19-05-2026"),
}
